Small change to include metatranscriptomic
biocore/mg-scripts pull request #100
Opened 2023-06-13 23:09 UTC by charles-cowart

2023-06-13 23:16 UTC, antgonza commented on sequence_processing_pipeline/QCJob.py
> +            True if header['Assay'] in meta_types else False)
I don't think `meta_types` is an accurate name; perhaps easier to just do:

`needs_adapter_trimming = header['Assay'] in [Pipeline.METAGENOMIC_PTYPE, Pipeline.METATRANSCRIPTOMIC_PTYPE]`

2023-06-13 23:16 UTC, antgonza requested changes
Any tests needed for this change?

2023-06-14 00:10 UTC, charles-cowart commented
> Any tests needed for this change?

It might be a little overkill but I added one that confirms Metatranscriptomic is a valid Assay type while an obviously invalid one raises an Error.

2023-06-14 00:37 UTC, antgonza commented on sequence_processing_pipeline/QCJob.py
> +            True if header['Assay'] in [Pipeline.METAGENOMIC_PTYPE,
I don't think the if/else is necessary here; could you remove it?

2023-06-14 01:47 UTC, antgonza approved these changes

2023-06-14 01:47 UTC, merged