WIP: Added support for replicates. Test needed.
biocore/mg-scripts pull request #101
Opened 2023-07-13 07:34 UTC by charles-cowart

This is how GenPrepFileJob will use the new functionality in metapool to transparently handle replicates. The code is here but I need to write a good test.

2023-07-21 04:39 UTC, charles-cowart commented
This PR depends on an update to metapool (https://github.com/biocore/metagenomics_pooling_notebook/pull/134). 134 is currently failing due to a Qiita dependency. This issue will be looked into shortly.

2023-08-03 16:51 UTC, charles-cowart commented
@antgonza Just a reminder this should ideally be reviewed after the changes to metapool are approved and merged and the url in setup.py is reverted to normal.

2023-08-04 16:24 UTC, antgonza requested changes

2023-08-04 16:24 UTC, antgonza commented on sequence_processing_pipeline/GenPrepFileJob.py
> +                fp = join(self.output_path, f"sheet{count}.txt")
would an underscore be helpful here? Like sheet_X.txt

2023-08-04 19:56 UTC, charles-cowart commented
@antgonza ready for re-review!

2023-08-04 20:00 UTC, antgonza requested changes
Sorry missed a line in my last review, I think this is it.

2023-08-04 20:03 UTC, charles-cowart commented on sequence_processing_pipeline/GenPrepFileJob.py
> +            count += 1
ah good catch! Sometimes I still think in C I guess. 😆

2023-08-04 20:16 UTC, merged