(WIP) Sequence Processing Pipeline package
biocore/mg-scripts pull request #15
Opened 2021-08-26 20:08 UTC by charles-cowart

A work-in-progress capturing the sequence-processing pipline in a package. This package will provide a command-line interface so it can be used standalone as well as part of Qiita or other projects. Human-filtering and Slurm submission functionality is currently being implemented.

Jeff's already reviewed this code, but I'll add him for completeness.

2021-09-23 00:16 UTC, antgonza reviewed
Some initial comments; haven't reviewed all the code ... more soon.

2021-09-23 00:20 UTC, charles-cowart commented on sequence_processing_pipeline/BCL2FASTQJob.py
> +        # TODO: Use Jinja template instead
Yoshiki thought it might be better to use a template of some kind. He and a student were using Jinja to do a similar thing and he mentioned it.

2021-09-23 17:57 UTC, ElDeveloper requested changes
- Suggest to merge torque and torque job.

2021-09-23 17:57 UTC, ElDeveloper commented on sequence_processing_pipeline/BCL2FASTQJob.py
> +
Add a check for the RTA complete file.

2021-09-23 17:57 UTC, ElDeveloper commented on sequence_processing_pipeline/BCL2FASTQJob.py
> +                                                 self.output_directory))
This command call should use the ppn value and maybe concatenate the whole string instead of using backslashes.

2021-09-23 17:57 UTC, ElDeveloper commented on sequence_processing_pipeline/BCL2FASTQJob.py
> +    def run(self, queue_name, node_count, nprocs, wall_time_limit):
Consider refactoring into the baseclass.

2021-09-23 17:57 UTC, ElDeveloper commented on sequence_processing_pipeline/BCLConvertJob.py
> +        lines.append("date '+%s' >> /{}/{}.log".format(self.root_dir, self.job_name))
Can you add a command copying the Stats file to the `/sequencing/complete_runs/run_id/...`

2021-09-23 17:57 UTC, ElDeveloper commented on sequence_processing_pipeline/BCL2FASTQJob.py
> +        lines.append('%s --sample-sheet %s \
Can you add a command copying the Stats file to the `/sequencing/complete_runs/run_id/...`

2021-09-23 17:57 UTC, ElDeveloper commented on sequence_processing_pipeline/HumanFilterJob.py
> +                    'ReverseAdapter': 'adapter_A', 'HumanFiltering': 'h_filter'}
This conversion should probably not happen altogether.

2021-09-23 17:57 UTC, ElDeveloper commented on sequence_processing_pipeline/HumanFilterJob.py
> +                l[index][key] = value
Suggest using Pandas' methods for converting to dict and casting the types. Maybe something like sheet.Bioinformatics.to_dict() and infer_types along the way.

2021-09-23 17:57 UTC, ElDeveloper commented on sequence_processing_pipeline/HumanFilterJob.py
> +        for root, dirs, files in walk(search_path):
```suggestion
        for sample in self.sample_sheet:
```

2021-09-23 17:59 UTC, antgonza reviewed
Another partial review, getting there.

2021-09-23 17:59 UTC, antgonza commented on sequence_processing_pipeline/BCL2FASTQJob.py
> +        lines.append("#PBS -l nodes=%d:ppn=%d" % (node_count, nprocs))
also global variable

2021-09-23 17:59 UTC, antgonza commented on sequence_processing_pipeline/BCL2FASTQJob.py
> +        lines.append("#PBS -l nodes=%d:ppn=%d" % (node_count, nprocs))
lines.append(f"#PBS -l nodes={node_count}:ppn={nprocs}")

2021-09-23 17:59 UTC, antgonza commented on sequence_processing_pipeline/BCL2FASTQJob.py
> +        #lines.append("#PBS -l pmem=10gb")
readd this line and use what's expected; also set that value as a global -> to change to conf

2021-09-23 17:59 UTC, antgonza commented on sequence_processing_pipeline/BCL2FASTQJob.py
> +        lines.append("date '+%s' > bcl2fastq.job.log")
remove lines for bcl2fastq.job.log

2021-09-23 17:59 UTC, antgonza commented on sequence_processing_pipeline/HumanFilterJob.py
> +class HumanFilterJob(TorqueJob):
rename HumanFilterJob -> QCJob ... add docstring to explain what it does

2021-09-23 17:59 UTC, antgonza commented on sequence_processing_pipeline/HumanFilterJob.py
> +        self.fpmmp_path = fpmmp_path
move fpmmp_path to global or config

2021-09-23 17:59 UTC, antgonza commented on sequence_processing_pipeline/HumanFilterJob.py
> +        self.mmi_db_path = mmi_db_path
use global or config for: mmi_db_path

2021-09-23 17:59 UTC, antgonza commented on sequence_processing_pipeline/HumanFilterJob.py
> +            fastq_files = self._find_fastq_files(project['project_name'])
replace to use the sample_sheet and remove function.

2021-09-23 20:17 UTC, ElDeveloper commented
- [ ] Remember to add `metapool` to setup.py. We'll need to make a release but we have a ticket open for that: https://github.com/biocore/metagenomics_pooling_notebook/issues/30

2021-09-23 20:17 UTC, ElDeveloper requested changes
- [x] Remember to add `metapool` to setup.py. We'll need to make a release but we have a ticket open for that: https://github.com/biocore/metagenomics_pooling_notebook/issues/30

2021-09-24 13:29 UTC, antgonza commented
@charles-cowart, note that I just added CI to this repo and it will not pass until the flake8 errors are fixed.

2021-09-28 22:54 UTC, wasade commented on sequence_processing_pipeline/ConvertJob.py
> +            lines.append(('%s '
I think this is the same as the if block?

2021-09-28 22:57 UTC, wasade commented on sequence_processing_pipeline/FastQCJob.py
> +        pass
Does this override a superclass method? If so, is it correct for run() to be a noop?

2021-10-05 17:41 UTC, antgonza commented
Thank you all for your help with this PR. I'm merging it so we can continue adding individual features as PRs. If you feel like anything is missing please open an issue.

2021-10-05 17:41 UTC, merged