Qsub fix
biocore/mg-scripts pull request #45
Opened 2021-11-04 00:02 UTC by charles-cowart

Added exit_status parsing for jobs
Added exit_status parsing for non-array jobs as they appear to exit with 'C' job-status, even when an error has occured.
ConvertJob() will now catch any PipelineErrors raised by run() and re-raise them as a ConvertJob-specific Error.
This error should help detect when bcl-convert has exited with 1.

2021-11-04 00:03 UTC, charles-cowart commented
Note that unittests will provide little coverage of the affected code.

2021-11-05 03:36 UTC, antgonza requested changes

2021-11-05 03:36 UTC, antgonza commented on sequence_processing_pipeline/ConvertJob.py
> +        # lines.append(f"#PBS -o localhost:{self.log_path}/qsub_stdout.log")
rm

2021-11-05 03:36 UTC, antgonza commented on sequence_processing_pipeline/ConvertJob.py
> +        job_info = self.qsub(self.job_script_path, None, None,
can you make sure that all calls to self.qsub are outside a try/except?

2021-11-05 03:36 UTC, antgonza commented on sequence_processing_pipeline/FastQCJob.py
> +        # lines.append(f"#PBS -o localhost:{log_path}_stdout.log")
rm

2021-11-05 03:36 UTC, antgonza commented on sequence_processing_pipeline/QCJob.py
> +        # lines.append(f"#PBS -o localhost:{log_path}_stdout.log")
rm

2021-11-09 01:37 UTC, charles-cowart commented
@antgonza Hi Antonio, can you please review this one more time? As you can see, there are no cases where qsub is being wrapped in a try/except in this codebase.

2021-11-09 13:52 UTC, merged